name: Authorization Add
description: Form for testing User Authorization Additions.
labels: user-info
title: "Add an New Authorized User"
body:
  - type: input
    id: email
    attributes:
      label: Add a New User
      description: Please enter your user name in the format user@domain.com
      placeholder: user@domain.com
    validations:
      required: true

  - type: checkboxes
    id: operations
    attributes:
      label: Operations
      description: Select the operations to allow
      options:
        - label: EESEventAdd
        - label: EESEventSrch
        - label: ESMAdd
        - label: Ping
