blank_issues_enabled: false
contact_links:
  - name: Support
    url: https://example.com/support
    about: Please visit our support page for assistance.

issue_template:
  - name: Test Form
    description: Authorization
    title: "[Update Authorization File] "
    labels: configuration
    file: test_form.yml
