name: Test Form
description: Authorization
title: "[Update Authorization File] "
labels: configuration
body:
  - type: input
    id: User
    attributes:
      label: Enter an user
      description: Enter a user name to add
      placeholder: user@doman.com
      required: true
      validations:
        regex: '^[a-z0-9._%+-]+@[a-z0-9.-]+\.[a-z]{2,}$'
        error: "Please enter a valid user profile"
      
