name: Test Form
description: Report an issue related to user information.
labels: ["user-info"]
body:
  - type: markdown
    attributes:
      value: |
        Please provide your user information in the format `user@domain.com`.
  - type: input
    id: user-name
    attributes:
      label: User Name
      description: Your user name in the format user@domain.com.
      placeholder: user@domain.com
    validations:
      required: true
      regex: "^[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\\.[a-zA-Z]{2,}$"
      error: "Please provide a valid email address (user@domain.com)."     
