name: Test Form
description: Form for testing User Authorization Updates.
labels: ["user-info"]
title: "[Authorized User Configuration]"
body:
  - type: input
    id: user_name
    attributes:
      label: User Name
      description: Please enter your user name
      placeholder: johndoe
    validations:
      required: true

  - type: dropdown
    id: user_dropdown
    attributes:
      label: Select User
      description: Choose a user from the list
      options:
        - IMSUser@jha-dev.com
        - Chris_co@jhadev.com
        - RandomUser@jackhenry.com
    validations:
      required: true

  - type: checkboxes
    id: operations
    attributes:
      label: Operations
      description: Select the operations to perform
      options:
        - label: EESEventAdd
        - label: EESEventSrch
        - label: ESMAdd
        - label: Ping
