name: Test Form
description: Form for testing User Authorization Updates.
labels: ["user-info"]
title: "[Authorized User Configuration]"
body:
  - type: input
    id: email
    attributes:
      label: Add a New User
      description: Please enter your user name in the format user@domain.com
      placeholder: user@domain.com
    validations:
      required: true

  - type: checkboxes
    id: operations
    attributes:
      label: Operations
      description: Select the operations to allow
      options:
        - label: EESEventAdd
        - label: EESEventSrch
        - label: ESMAdd
        - label: Ping
