name: Update Issue Form with Options

on:
  push:
    paths:
      - '.github/ISSUE_TEMPLATE/authorization.yaml'

jobs:
  update-issue-form:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install yq
        run: sudo apt-get install -y yq

      - name: Read options from YAML
        id: read_options
        run: |
          names=$(yq e '.[] | .Name' .github/ISSUE_TEMPLATE/authorization.yaml)
          echo "::set-output name=names::${names}"

      - name: Update issue form
        run: |
          yq e '.body[0].attributes.options = env(names)' -i .github/ISSUE_TEMPLATE/test_form.yml
