name: Extract Input Value

on:
  issues:
    types: [opened]

jobs:
  extract_value:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Log Issue Body
        run: |
          echo "The issue body is: "
          echo "${{ github.event.issue.body }}"

      - name: Get Issue Data
        id: issue_data
        run: |
          echo "user_name=$(echo '${{ github.event.issue.body }}' | awk '/### Add a New User/{f=1;next} /###/{f=0} f')" >> $GITHUB_OUTPUT

      - name: Log User Name
        run: |
          echo "The user name is ${{ steps.issue_data.outputs.user_name }}"
