name: Validate Email Format

on:
  issues:
    types: [opened]

jobs:
  validate-email:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Extract Email
        id: extract_email
        run: |
          email=$(jq -r '.issue.body' "$GITHUB_EVENT_PATH" | grep -oP '(?<=Email Address: ).*')
          echo "::set-output name=email::$email"

      - name: Validate Email
        id: validate_email
        run: |
          email="${{ steps.extract_email.outputs.email }}"
          if [[ ! "$email" =~ ^[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\.[a-zA-Z]{2,}$ ]]; then
            echo "Invalid email format: $email"
            exit 1
          fi

      - name: Close Issue
        if: failure()
        uses: peter-evans/close-issue@v2
        with:
          issue-number: ${{ github.event.issue.number }}
          comment: "The email address provided is invalid. Please use the format user@domain.com."
