name: Validate Email Format

on:
  issues:
    types: [opened]

permissions:
  issues: write

jobs:
  validate-email:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install GitHub CLI
        run: sudo apt-get install -y gh

      - name: Extract Email
        id: extract_email
        run: |
          email=$(jq -r '.issue.body' "$GITHUB_EVENT_PATH" | grep -oP '(?<=Email Address: ).*')
          echo "::set-output name=email::$email"

      - name: Validate Email
        id: validate_email
        run: |
          email="${{ steps.extract_email.outputs.email }}"
          if [[ ! "$email" =~ ^[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\.[a-zA-Z]{2,}$ ]]; then
            echo "Invalid email format: $email"
            exit 1

      - name: Close Issue
        if: failure()
        run: |
          gh issue close ${{ github.event.issue.number }} --comment "The email address provided is invalid. Please use the format user@domain.com."
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
