name: Extract Input Value

on:
  issues:
    types: [opened]

jobs:
  extract_value:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Get Issue Data
        id: issue_data
        run: |
          echo "user_name=$(echo '${{ toJSON(github.event.issue.body) }}' | jq -r '.| select(.id == \"email\") | .attributes.value')" >> $GITHUB_OUTPUT

      - name: Log User Name
        run: |
          echo "The user name is ${{ steps.issue_data.outputs.user_name }}"
