name: Extract Input Value

on:
  issues:
    types: [opened]

jobs:
  extract_value:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Get Issue Data
        id: issue_data
        run: |
          echo "user_name=$(echo '${{ github.event.issue.body }}' | sed -n '/### Add a New User/,/###/p')" >> $GITHUB_OUTPUT

      - name: Log Extracted Section
        run: |
          echo "The extracted section is: "
          echo "${{ steps.issue_data.outputs.user_name }}"
