name: Extract Email

on:
  issues:
    types: [opened]

permissions:
  issues: write

jobs:
  extract-email:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install jq and GitHub CLI
        run: |
          sudo apt-get update
          sudo apt-get install -y jq gh

      - name: Debug GITHUB_EVENT_PATH
        run: cat "$GITHUB_EVENT_PATH"

      - name: Extract Email
        id: extract_email
        run: |
          email=$(jq -r '.issue.body | split("\n") | map(select(test("^[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\\.[a-zA-Z]{2,}$"))) | .[0]' "$GITHUB_EVENT_PATH")
          if [ -z "$email" ]; then
            echo "Email not found"
            exit 1
          fi
          echo "Extracted email: $email"
          echo "email=$email" >> $GITHUB_ENV

