name: Validate Email Format

on:
  issues:
    types: [opened]

permissions:
  issues: write

jobs:
  validate-email:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install yq and GitHub CLI
        run: |
          sudo apt-get update
          sudo apt-get install -y yq gh

      - name: Debug GITHUB_EVENT_PATH
        run: cat "$GITHUB_EVENT_PATH"

      - name: Extract Email
        id: extract_email
        run: |
          email=$(yq e '.body[] | select(.id == "email") | .attributes.value' "$GITHUB_EVENT_PATH")
          if [ -z "$email" ]; then
            echo "Email not found"
            exit 1
          fi
          echo "Extracted email: $email"
          echo "::set-output name=email::$email"

      - name: Validate Email
        id: validate_email
        run: |
          email="${{ steps.extract_email.outputs.email }}"
          echo "Validating email: $email"
          if [[ ! "$email" =~ ^[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\.[a-zA-Z]{2,}$ ]]; then
            echo "Invalid email format: $email"
            exit 1
          else
            echo "Valid email format: $email"

      - name: Close Issue
        if: failure()
        run: |
          gh issue close ${{ github.event.issue.number }} --comment "The email address provided is invalid. Please use the format user@domain.com."
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
